# pipelines/app-cd-pipeline.yml

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'acr-connection'
  imageRepository: 'myazureproject'
  containerRegistry: 'azureacrt14.azurecr.io'
  dockerfilePath: 'app/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'azureacrt144967-auth'
  vmImageName: 'ubuntu-22.04'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push image to ACR
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

    - task: PublishPipelineArtifact@1
      displayName: Publish manifests folder
      inputs:
        targetPath: '$(Build.SourcesDirectory)/manifests'
        artifact: manifests

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'acr-aks-pipeline.default'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: manifests
              targetPath: '$(Pipeline.Workspace)/manifests'

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: |
                azureacrt14.azurecr.io/myazureproject:$(Build.BuildId)
              imagePullSecrets: 'azureacrt144967-auth'
